### ISSUE TITLE
Logged in (iCloud) but no calendars

### ISSUE THREAD

**Issue by mjsalam** [Vaccarini-Lorenzo/MagicCalendar#30]
Hi,

I connected via iCloud and it says logged in but the calendars dropdown does nothing.  Tried a few times.   I also tried Google and that did give me a selection of calendars but I really want the two-way sync.  The plugin looks really excellent - hoping I can get it working!

![image](https://github.com/Vaccarini-Lorenzo/MagicCalendar/assets/24506764/744e6450-9b7b-4449-bd4b-6731466b2973)

![image](https://github.com/Vaccarini-Lorenzo/MagicCalendar/assets/24506764/44b5f4b3-1ce0-47a3-8817-5a2df2b7bcfe)

**Comment by mjsalam** [comment]
Quick update ... the inline calendar does appear to be working though.

**Comment by mjsalam** [comment]
Would love to be able to switch axis.   (So dates are horizontal and hours are vertical.)

**Comment by Vaccarini-Lorenzo** [comment]
Hi Mark, thank you for taking the time to open this issue.
What happens if you click on the calendar dropdown? I'm trying to replicate the issue locally but without success.
Would you mind checking the console too? To open it just click ```cmd+option+I```.
I'll take note about the request of switching axis and I'll work on it as soon as possible. 
Lorenzo

**Comment by Vaccarini-Lorenzo** [comment]
Close due to inactivity. Feel free to reopen it if anything changes.
